sudo: required

services:
  - docker

language: php
php:
  - 5.5

before_install:
  - composer self-update
  - mkdir -p "/tmp/PHPloyTestWorkspace/sftp_share/share"
  - mkdir -p "/tmp/PHPloyTestWorkspace/ftp_share/share"
  - sudo chmod -R 777 "/tmp/PHPloyTestWorkspace/ftp_share"
  - docker run --name sftp_testserver -d -v /tmp/PHPloyTestWorkspace/sftp_share:/home/sftpuser 	-p 2222:22 atmoz/sftp sftpuser:password:$(id -u)
  - docker run --name ftp_testserver -d -v /tmp/PHPloyTestWorkspace/ftp_share:/home/ftpusers/ftpuser -v $TRAVIS_BUILD_DIR/tests/ftp_setup.sh:/root/ftp_setup.sh -p 21:21 -p 30000-30009:30000-30009 -e "PUBLICHOST=localhost"  stilliard/pure-ftpd:hardened /root/ftp_setup.sh

install:
  - travis_retry composer install --no-interaction --prefer-source

script: ./vendor/bin/phpunit tests
